-- return {
--   "kdheepak/lazygit.nvim",
--   cmd = {
--     "LazyGit",
--     "LazyGitConfig",
--     "LazyGitCurrentFile",
--     "LazyGitFilter",
--     "LazyGitFilterCurrentFile",
--   },
--   -- Optional for floating window border decoration
--   dependencies = {
--     "nvim-lua/plenary.nvim",
--   },
--   -- Setting the keybinding for LazyGit with 'keys' is recommended in
--   -- order to load the plugin when the key is pressed
--   keys = {
--     { "<leader>gg", "<cmd>LazyGit<cr>", desc = "LazyGit" },
--   },
-- }
--
return {}
