-- For `plugins/markview.lua` users.
--
return {}
-- return {
--   "OXY2DEV/markview.nvim",
--   lazy = false,
--
--   -- Completion for `blink.cmp`
--   -- dependencies = { "saghen/blink.cmp" },
-- }
-- return {
--   "dhruvasagar/vim-table-mode",
--   -- init = function()
--   --   vim.g.table_mode_corner = "|"
--   -- end,
-- }
