return {}
-- set up debug for lua and fix this later
-- return {
--   "lucaSartore/nvim-dap-exception-breakpoints",
--   dependencies = { "mfussenegger/nvim-dap" },
--
--   config = function()
--     local set_exception_breakpoints = require("nvim-dap-exception-breakpoints")
--
--     vim.api.nvim_set_keymap(
--       "n",
--       "<leader>dx",
--       "",
--       { desc = "[D]ebug [x]ondition breakpoints", callback = set_exception_breakpoints }
--     )
--   end,
-- }
