-- return {
--   "pmizio/typescript-tools.nvim",
--   dependencies = { "nvim-lua/plenary.nvim", "neovim/nvim-lspconfig" },
--   ft = { "typescript", "typescriptreact", "javascript", "javascriptreact" },
--   opts = {
--     settings = {
--       -- Spawn a separate diagnostic server for better performance
--       separate_diagnostic_server = true,
--       publish_diagnostic_on = "insert_leave",
--       -- Enable function call completions with parameter snippets
--       complete_function_calls = true,
--       -- Inlay hints configuration
--       tsserver_file_preferences = {
--         includeInlayParameterNameHints = "literals",
--         includeInlayParameterNameHintsWhenArgumentMatchesName = false,
--         includeInlayFunctionParameterTypeHints = true,
--         includeInlayVariableTypeHints = false,
--         includeInlayVariableTypeHintsWhenTypeMatchesName = false,
--         includeInlayPropertyDeclarationTypeHints = true,
--         includeInlayFunctionLikeReturnTypeHints = true,
--         includeInlayEnumMemberValueHints = true,
--       },
--       -- Auto-close JSX tags
--       jsx_close_tag = {
--         enable = true,
--         filetypes = { "javascriptreact", "typescriptreact" },
--       },
--     },
--   },
--   keys = {
--     { "<leader>co", "<cmd>TSToolsOrganizeImports<cr>", desc = "Organize Imports" },
--     { "<leader>cM", "<cmd>TSToolsAddMissingImports<cr>", desc = "Add Missing Imports" },
--     { "<leader>cR", "<cmd>TSToolsRemoveUnused<cr>", desc = "Remove Unused Imports" },
--     { "<leader>cF", "<cmd>TSToolsFixAll<cr>", desc = "Fix All Diagnostics" },
--     { "<leader>cD", "<cmd>TSToolsGoToSourceDefinition<cr>", desc = "Go to Source Definition" },
--     { "<leader>cf", "<cmd>TSToolsFileReferences<cr>", desc = "File References" },
--     { "<leader>cr", "<cmd>TSToolsRenameFile<cr>", desc = "Rename File" },
--     { "<leader>cs", "<cmd>TSToolsSortImports<cr>", desc = "Sort Imports" },
--   },
-- }
return {}
