-- return {
--   "neovim/nvim-lspconfig",
--   opts = {
--     servers = {
--       vtsls = {
--         settings = {
--           javascript = {
--             implicitProjectConfig = {
--               checkJs = false,
--               include = { "src/**/*" },
--             },
--           },
--           typescript = {
--             implicitProjectConfig = {
--               strictNullChecks = false,
--               include = { "src/**/*" },
--             },
--           },
--         },
--       },
--     },
--   },
-- }
return {}
